services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d:ro
    networks:
      - menu
    ports:
      - "5432:5432"

  app:
    build: .
    command: npm run dev
    working_dir: /app
    environment:
      DATABASE_URL: "postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@db:5432/${DATABASE_NAME}"
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${APP_PORT}
      BCRYPT_SALT_ROUNDS: ${BCRYPT_SALT_ROUNDS}
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db
    networks:
      - menu

volumes:
  postgres-data:

networks:
  menu:
